import { apiJj } from './allUrl'

export default {
    sign_in : `${ apiJj }sign_in`,
    set_area : `${ apiJj }set_area`,
    ip_area : `${ apiJj }ip_area`,
    geoCoder : `${ apiJj }geoCoder`,
    cate : `${ apiJj }cate`,
    user :  `${ apiJj }user/`,
    shoppingCart : `${ apiJj }shopping_cart`,
    photos : `${ apiJj }photos`,
    goodCates : `${ apiJj }cate`,
    recommendedActivities:`${ apiJj }get_goods`,
    recommendedGoods:`${ apiJj }goods_browse_records`,
    getAttributes : `${ apiJj }getAttributes`,
    goodList : `${ apiJj }goods`,
    dataAudit : `${ apiJj }merchants`,
    userOne : `${ apiJj }user/1`,
    userMess : `${ apiJj }user`,
    getServiceCategories : `${ apiJj }getServiceCategories`,
    getSms : `${ apiJj }get_sms`,
    geoCoder : `${ apiJj }geoCoder`,
    orders :  `${ apiJj }orders`,
    homeDate : `${ apiJj }get_home_date`,
    browseRecords : `${ apiJj }browse_records`,
    works : `${ apiJj }works`,
    demands : `${ apiJj }demands`,
    notes : `${ apiJj }notes`,
    forums : `${ apiJj }forums`,
    ip_area : `${ apiJj }ip_area`,
    forumReview : `${ apiJj }forum_review`,
    get_ads : `${ apiJj }get_ads`,
    get_brands : `${ apiJj }get_brands`,
    work_orders : `${ apiJj }work_orders`,
    work_order_details : `${ apiJj }work_order_details`,
    diys : `${ apiJj }diys`,
    secondary_payment : `${ apiJj }secondary_payment`,
    shop_cancel_order : `${ apiJj }shop_cancel_order`,
    cancel_order : `${ apiJj }cancel_order`,
    work_cancel_refund : `${ apiJj }work_cancel_refund`,
    cancel_refund : `${ apiJj }cancel_refund`,
    order_refund : `${ apiJj }order_refund`,
    merchant_delivery : `${ apiJj }merchant_delivery`,
    edit_price : `${ apiJj }edit_price`,
    edit_work_order_price : `${ apiJj }edit_work_order_price`,
    merchantServiceRefund : `${ apiJj }merchant_operation_refund_order`,
    merchantGoodsRefund : `${ apiJj }merchant_operation_goods_refund_order`,
    work_reviews : `${ apiJj }work_reviews`
}